spring.application.name=vnpay
server.port=8080

# C?u hình VNPay c?a ch? Lunar
vnpay.tmn-code=2QX77WIG
vnpay.hash-secret=964W6H9TDP77K6L9K9L6H9TDP77K6L9K
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.api-url=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
vnpay.return-url=http://localhost:8080/vnpay-callback